name: Publish to VS Code Marketplace

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Package Extension
      run: npm run package

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "*.vsix"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to VS Code Marketplace
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}